/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.frmPesquisarProdutos;
import Model.CriaTabelaClientes;
import Model.CriaTabelaFornecedores;
import Model.CriaTabelaProdutos;
import Model.Pilha;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author UNIFAFIBE
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form formPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //Mudar a linha de baixo de acordo com o caminho da db
    String route = "C:\\Users\\User\\Desktop\\Inter 2.3\\mart.db";
    Connection c = null;
    Statement stat = null;
    String op;

    public void connect() {
        try {
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:mart.db");
            if (c != null) {
                System.out.println("Connected to db.");
            }
        } catch (SQLException ex) {
            System.err.println("Couldn't connect." + ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CriaTabelaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        img_logo = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        btnCadastrarCliente = new javax.swing.JMenuItem();
        btnPesquisarCliente = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        btnCadastrarProduto = new javax.swing.JMenuItem();
        btnPesquisarProduto = new javax.swing.JMenuItem();
        btnRelatorio = new javax.swing.JMenuItem();
        menuFornecedores = new javax.swing.JMenu();
        btnCadastrarFornecedores = new javax.swing.JMenuItem();
        btnPesquisarFornecedores = new javax.swing.JMenuItem();
        menuFerramenta = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M.A.R.T Sistemas");
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        menuCliente.setText("Clientes");

        btnCadastrarCliente.setText("Cadastrar");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(btnCadastrarCliente);

        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(btnPesquisarCliente);

        menuPrincipal.add(menuCliente);

        menuProdutos.setText("Produtos");

        btnCadastrarProduto.setText("Cadastrar");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });
        menuProdutos.add(btnCadastrarProduto);

        btnPesquisarProduto.setText("Pesquisar");
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });
        menuProdutos.add(btnPesquisarProduto);

        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        menuProdutos.add(btnRelatorio);

        menuPrincipal.add(menuProdutos);

        menuFornecedores.setText("Fornecedores");

        btnCadastrarFornecedores.setText("Cadastrar");
        btnCadastrarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFornecedoresActionPerformed(evt);
            }
        });
        menuFornecedores.add(btnCadastrarFornecedores);

        btnPesquisarFornecedores.setText("Pesquisar");
        btnPesquisarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFornecedoresActionPerformed(evt);
            }
        });
        menuFornecedores.add(btnPesquisarFornecedores);

        menuPrincipal.add(menuFornecedores);

        menuFerramenta.setText("Ferramentas");

        jMenuItem1.setText("Atualiza Estrutura do Banco");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuFerramenta.add(jMenuItem1);

        jMenuItem2.setText("Limpar todas tabelas SQL");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuFerramenta.add(jMenuItem2);

        menuPrincipal.add(menuFerramenta);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addComponent(img_logo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(img_logo)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        frmCliente cdc = new frmCliente();
        cdc.setVisible(true);
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
       frmPesquisaClientes form = new frmPesquisaClientes(); 
       form.setVisible(true);   
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        frmCadastrarProduto form = new frmCadastrarProduto();
        form.setVisible(true);
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
        
         CriaTabelaFornecedores criaForn = new CriaTabelaFornecedores();
        try {
            criaForn.CriaTabelaFornecedores_DB();
        } catch (Exception e) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, e);
        }
        
        try
        {
            CriaTabelaClientes cria = new CriaTabelaClientes();
        try {
            cria.CriaTabelaCliente_DB();
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        CriaTabelaProdutos criar = new CriaTabelaProdutos();
        try {
            criar.CriaTabelaProduto_DB();
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null ,"A estrutura foi atualizada");
        } 
        catch(Exception e)
        {
        
            
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
        frmPesquisarProdutos form = new frmPesquisarProdutos();
        form.setVisible(true);
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
                 
         connect();
         try{
            stat = c.createStatement();
            op = "DELETE from clientes";
            System.out.println(op);            
            stat.executeUpdate(op);       
            stat.close();
         
        } catch (SQLException e) {
                      
        }
        connect();
        try {               
            
            stat = c.createStatement();
            op = "DELETE from produtos";
            System.out.println(op);            
            stat.executeUpdate(op);       
            stat.close();
            
        } catch (SQLException e) {
                   
        }      
        connect();
        try {               
            
            stat = c.createStatement();
            op = "DELETE from Fornecedores";
            System.out.println(op);            
            stat.executeUpdate(op);       
            stat.close();
            
        } catch (SQLException e) {
                   
        }  
        
        
       JOptionPane.showMessageDialog(null ,"Todas tabelas SQL foram limpas");
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnCadastrarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFornecedoresActionPerformed
        frmCadastrarFornecedor form = new frmCadastrarFornecedor();
        form.setVisible(true);
    }//GEN-LAST:event_btnCadastrarFornecedoresActionPerformed

    private void btnPesquisarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFornecedoresActionPerformed
        frmPesquisarFornecedor form = new frmPesquisarFornecedor();
        form.setVisible(true);
    }//GEN-LAST:event_btnPesquisarFornecedoresActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        frmCadastrarProduto novaPil = new frmCadastrarProduto();
        if (frmCadastrarProduto.pil.Vazia()) {
            JOptionPane.showMessageDialog(null ,"Nenhuma alteração no cadastro de produtos foi feita recentemente.");
        } else {
            frmRelatorioProdutos relatorio = new frmRelatorioProdutos();
            relatorio.setVisible(true);
        }      
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCadastrarCliente;
    private javax.swing.JMenuItem btnCadastrarFornecedores;
    private javax.swing.JMenuItem btnCadastrarProduto;
    private javax.swing.JMenuItem btnPesquisarCliente;
    private javax.swing.JMenuItem btnPesquisarFornecedores;
    private javax.swing.JMenuItem btnPesquisarProduto;
    private javax.swing.JMenuItem btnRelatorio;
    private javax.swing.JLabel img_logo;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuFerramenta;
    private javax.swing.JMenu menuFornecedores;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuProdutos;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
